import type { ReactNode } from 'react';
import { AlertCircle, Archive, ChevronLeft, ChevronRight, Loader2, Plus, Search, SlidersHorizontal, X } from 'lucide-react';
import { AppHeader, PageBody, Screen } from '@/components/ui/Page';

export type AdminListRecord = { id: string; name: string; active: boolean; relatedCount?: number };

export function AdminPageShell({ title, subtitle, onBack, children }: { title: string; subtitle: string; onBack: () => void; children: ReactNode }) {
  return <Screen showStatusBar={false}><AppHeader title={title} onBack={onBack} prominent className="rounded-b-[22px] bg-gradient-to-br from-[#0D47A1] to-[#1565C0] shadow-md lg:hidden" /><div className="hidden border-b border-slate-200 bg-white lg:block"><div className="mx-auto max-w-7xl px-6 py-6 xl:px-8"><h1 className="text-2xl font-extrabold tracking-tight text-slate-900">{title}</h1><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div></div><PageBody className="lg:max-w-7xl lg:px-6 lg:pb-10 lg:pt-6 xl:px-8">{children}</PageBody></Screen>;
}

export function ReadOnlyBanner({ children = 'Read only — Organisation structure is managed by Super Admin.' }: { children?: ReactNode }) {
  return <div className="mb-4 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2.5 text-xs font-medium text-amber-800">{children}</div>;
}

export function SearchAndFilterBar({ search, onSearchChange, status, onStatusChange }: { search: string; onSearchChange: (value: string) => void; status: 'all' | 'active' | 'inactive'; onStatusChange: (value: 'all' | 'active' | 'inactive') => void }) {
  return <div className="mb-3 flex gap-2 lg:max-w-2xl"><label className="flex min-w-0 flex-1 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2.5"><Search className="h-4 w-4 shrink-0 text-slate-400" /><input value={search} onChange={(event) => onSearchChange(event.target.value)} placeholder="Search" className="min-w-0 flex-1 bg-transparent text-sm outline-none" /></label><label className="flex items-center gap-1 rounded-xl border border-slate-200 bg-white px-2 text-xs font-semibold text-slate-600"><SlidersHorizontal className="h-4 w-4" /><span className="sr-only">Status</span><select value={status} onChange={(event) => onStatusChange(event.target.value as 'all' | 'active' | 'inactive')} className="max-w-20 bg-transparent outline-none"><option value="all">All</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div>;
}

export function StatusBadge({ active, label }: { active: boolean; label?: string }) { return <span className={`rounded-full px-2 py-1 text-[10px] font-bold ${active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{label ?? (active ? 'Active' : 'Inactive')}</span>; }
export function EmptyState({ title = 'No records to show', message = 'Records will appear here once this administration area is configured.' }: { title?: string; message?: string }) { return <div className="rounded-2xl border border-dashed border-slate-200 bg-white px-5 py-10 text-center"><p className="text-sm font-bold text-slate-800">{title}</p><p className="mx-auto mt-1 max-w-xs text-xs leading-5 text-slate-500">{message}</p></div>; }
export function LoadingSkeleton({ rows = 4 }: { rows?: number }) { return <div className="space-y-2">{Array.from({ length: rows }, (_, index) => <div key={index} className="h-16 animate-pulse rounded-xl bg-slate-200" />)}</div>; }
export function ErrorState({ message, onRetry }: { message: string; onRetry?: () => void }) { return <div className="rounded-2xl bg-red-50 p-4 text-center"><AlertCircle className="mx-auto h-5 w-5 text-red-600" /><p className="mt-2 text-sm font-semibold text-red-800">Could not load records</p><p className="mt-1 text-xs text-red-700">{message}</p>{onRetry && <button type="button" onClick={onRetry} className="mt-3 text-sm font-bold text-red-700">Retry</button>}</div>; }

export function PaginationControls({ page, pageSize, total, onPageChange }: { page: number; pageSize: number; total: number; onPageChange: (page: number) => void }) {
  const lastPage = Math.max(0, Math.ceil(total / pageSize) - 1);
  if (total <= pageSize) return null;
  return <div className="mt-3 flex items-center justify-between text-xs text-slate-600"><span>Page {page + 1} of {lastPage + 1}</span><div className="flex gap-1"><button type="button" disabled={page === 0} onClick={() => onPageChange(page - 1)} className="rounded-lg border p-2 disabled:opacity-40" aria-label="Previous page"><ChevronLeft className="h-4 w-4" /></button><button type="button" disabled={page >= lastPage} onClick={() => onPageChange(page + 1)} className="rounded-lg border p-2 disabled:opacity-40" aria-label="Next page"><ChevronRight className="h-4 w-4" /></button></div></div>;
}

export function MasterDataList<T extends AdminListRecord>({ records, total, page, pageSize, search, onSearchChange, status, onStatusChange, onPageChange, loading = false, error, onRetry, onSelect, onAdd, emptyMessage }: { records: T[]; total: number; page: number; pageSize: number; search: string; onSearchChange: (value: string) => void; status: 'all' | 'active' | 'inactive'; onStatusChange: (value: 'all' | 'active' | 'inactive') => void; onPageChange: (page: number) => void; loading?: boolean; error?: string | null; onRetry?: () => void; onSelect?: (record: T) => void; onAdd?: () => void; emptyMessage?: string }) {
  return <section className="rounded-2xl bg-white p-3 shadow-sm lg:p-4"><div className="mb-3 flex items-center justify-between gap-2"><p className="text-xs text-slate-500">{loading ? 'Loading records…' : `${total} record${total === 1 ? '' : 's'}`}</p>{onAdd && <button type="button" onClick={onAdd} className="flex min-h-10 items-center gap-1 rounded-xl bg-blue-600 px-3 text-xs font-bold text-white"><Plus className="h-4 w-4" />Add</button>}</div><SearchAndFilterBar search={search} onSearchChange={onSearchChange} status={status} onStatusChange={onStatusChange} />{loading ? <LoadingSkeleton /> : error ? <ErrorState message={error} onRetry={onRetry} /> : records.length === 0 ? <EmptyState message={emptyMessage} /> : <div className="divide-y divide-slate-100"><div className="hidden grid-cols-[minmax(0,1fr)_180px_110px] gap-4 border-y border-slate-200 bg-slate-50 px-3 py-2 text-[10px] font-bold uppercase tracking-wide text-slate-500 lg:grid"><span>Record</span><span>Related records</span><span>Status</span></div>{records.map((record) => <button key={record.id} type="button" onClick={() => onSelect?.(record)} disabled={!onSelect} className="flex min-h-16 w-full items-center gap-3 py-3 text-left transition hover:bg-blue-50/40 disabled:cursor-default lg:grid lg:grid-cols-[minmax(0,1fr)_180px_110px] lg:px-3"><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-slate-800">{record.name}</span>{record.relatedCount !== undefined && <span className="mt-0.5 block text-xs text-slate-500 lg:hidden">{record.relatedCount} related record{record.relatedCount === 1 ? '' : 's'}</span>}</span><span className="hidden text-sm text-slate-600 lg:block">{record.relatedCount ?? '—'}</span><StatusBadge active={record.active} /></button>)}</div>}<PaginationControls page={page} pageSize={pageSize} total={total} onPageChange={onPageChange} /></section>;
}

export function DetailDrawer({ open, title, onClose, children }: { open: boolean; title: string; onClose: () => void; children: ReactNode }) { if (!open) return null; return <div className="fixed inset-0 z-50 flex items-end bg-slate-950/40 lg:items-center lg:justify-center lg:p-6" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section role="dialog" aria-modal="true" aria-label={title} className="w-full rounded-t-3xl bg-white p-5 shadow-2xl lg:max-h-[calc(100vh-3rem)] lg:max-w-2xl lg:overflow-y-auto lg:rounded-2xl lg:p-6"><div className="mb-4 flex items-center justify-between"><h2 className="text-base font-bold text-slate-900">{title}</h2><button type="button" onClick={onClose} aria-label="Close details" className="rounded-full p-2 text-slate-500 hover:bg-slate-100"><X className="h-5 w-5" /></button></div>{children}</section></div>; }
export function ConfirmArchiveDialog({ open, title, reason, onReasonChange, onCancel, onConfirm, working = false }: { open: boolean; title: string; reason: string; onReasonChange: (value: string) => void; onCancel: () => void; onConfirm: () => void; working?: boolean }) { if (!open) return null; return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><section role="alertdialog" aria-modal="true" className="w-full max-w-sm rounded-2xl bg-white p-5"><Archive className="h-6 w-6 text-amber-600" /><h2 className="mt-3 text-base font-bold text-slate-900">Archive {title}?</h2><p className="mt-1 text-sm text-slate-600">Referenced records are deactivated, never permanently deleted.</p><label className="mt-4 block text-xs font-semibold text-slate-600">Reason<textarea value={reason} onChange={(event) => onReasonChange(event.target.value)} className="mt-1 min-h-20 w-full rounded-xl border border-slate-200 p-2 text-sm" /></label><div className="mt-5 flex gap-2"><button type="button" onClick={onCancel} disabled={working} className="flex-1 rounded-xl border py-2.5 text-sm font-semibold">Cancel</button><button type="button" onClick={onConfirm} disabled={working || !reason.trim()} className="flex-1 rounded-xl bg-amber-600 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{working ? <Loader2 className="mx-auto h-4 w-4 animate-spin" /> : 'Archive'}</button></div></section></div>; }
