import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { LockKeyhole } from 'lucide-react';
import { api, type AppRole, type NotificationDeliveryReportRow, type NotificationDeliveryReportSummary, type OperatorActivityReportRow, type OperatorActivityReportSummary } from '@/services/api';
import { hasCapability } from '@/security/permissions';
import { useApp } from '@/context/AppContext';
import { getReportPeriodDates, getReportPeriodLabel, getReportRangeIso, ReportActions, ReportFilters, ReportPageShell, ReportPreview, type ReportColumn, type ReportFilterValues, type ReportResource, type ReportSummaryCard } from '@/components/reports';

const PAGE_SIZE = 50;
const INITIAL_PERIOD = getReportPeriodDates('today');
type Loaded = { filters: ReportFilterValues; page: number; total: number };
function formatIst(value: string): string { return new Intl.DateTimeFormat('en-IN', { timeZone: 'Asia/Kolkata', dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); }

function useAdminRole(): AppRole | null { const [role, setRole] = useState<AppRole | null>(null); useEffect(() => { let cancelled = false; void api.getMyRole().then((value) => { if (!cancelled) setRole(value); }).catch(() => { if (!cancelled) setRole(null); }); return () => { cancelled = true; }; }, []); return role; }
function AdminOnly({ title, onBack }: { title: string; onBack: () => void }) { const ref = useRef<HTMLDivElement>(null); return <ReportPageShell title={title} subtitle="Administrative report" onBack={onBack} contentRef={ref} filters={<div />}><div className="flex items-center gap-3 py-8 text-sm text-slate-600"><LockKeyhole className="h-5 w-5 text-red-600" />This report is available to authorised administrators only.</div></ReportPageShell>; }

export function OperatorActivityReportPage({ onBack }: { onBack: () => void }) {
  const role = useAdminRole(); const { stations } = useApp(); const ref = useRef<HTMLDivElement>(null); const generation = useRef(0);
  const [filters, setFilters] = useState<ReportFilterValues>({ stationId: '', feederId: '', period: 'today', ...INITIAL_PERIOD });
  const [resource, setResource] = useState<ReportResource<OperatorActivityReportRow>>({ rows: [], loading: false, error: null, generatedAt: null });
  const [summary, setSummary] = useState<OperatorActivityReportSummary | null>(null); const [loaded, setLoaded] = useState<Loaded | null>(null);
  const load = useCallback((next: ReportFilterValues, page: number, includeSummary: boolean) => { const request = ++generation.current; const { startIso, endIso } = getReportRangeIso(next); const stationId = next.stationId || null; setResource((current) => ({ ...current, loading: true, error: null })); void (includeSummary ? Promise.all([api.getOperatorActivityReportPage(startIso, endIso, page, PAGE_SIZE, stationId), api.getOperatorActivityReportSummary(startIso, endIso, stationId)]) : Promise.all([api.getOperatorActivityReportPage(startIso, endIso, page, PAGE_SIZE, stationId), Promise.resolve(null)])).then(([detail, nextSummary]) => { if (request !== generation.current) return; if (nextSummary) setSummary(nextSummary); setLoaded({ filters: next, page, total: detail.total }); setResource({ rows: detail.rows, loading: false, error: null, generatedAt: new Date() }); }).catch((error: unknown) => { if (request === generation.current) setResource((current) => ({ ...current, loading: false, error: error instanceof Error ? error.message : 'Failed to generate the Operator Activity report.' })); }); }, []);
  const generate = useCallback(() => { if (hasCapability(role, 'view_all_audit') && !resource.loading) load(filters, 0, true); }, [filters, load, resource.loading, role]);
  const columns = useMemo<ReportColumn<OperatorActivityReportRow>[]>(() => [
    { id: 'operator', label: 'Operator ID', value: (row) => row.operator_id ?? 'Not recorded', csvValue: (row) => row.operator_id }, { id: 'station', label: 'Station', value: (row) => row.station_name, csvValue: (row) => row.station_name }, { id: 'feeder', label: 'Feeder', value: (row) => row.feeder_name ?? 'Not recorded', csvValue: (row) => row.feeder_name },
    { id: 'event', label: 'Reading time (IST)', value: (row) => formatIst(row.actual_event_time), csvValue: (row) => formatIst(row.actual_event_time) }, { id: 'created', label: 'Created (IST)', value: (row) => formatIst(row.created_at), csvValue: (row) => formatIst(row.created_at) }, { id: 'updated', label: 'Last updated (IST)', value: (row) => formatIst(row.updated_at), csvValue: (row) => formatIst(row.updated_at) },
    { id: 'state', label: 'Row state', value: (row) => row.activity_state === 'UPDATED' ? 'Subsequently updated' : 'Created', csvValue: (row) => row.activity_state },
  ], []);
  const cards = useMemo<ReportSummaryCard[]>(() => summary ? [{ label: 'Entries created', value: String(summary.entries_created), tone: 'blue' }, { label: 'Rows subsequently updated', value: String(summary.rows_subsequently_updated), tone: 'orange' }, { label: 'Missing expected entries', value: String(summary.missing_expected_entries), tone: summary.missing_expected_entries ? 'red' : 'green' }, { label: 'Active operators', value: String(summary.operators_active), detail: `${summary.stations_active} stations`, tone: 'blue' }] : [], [summary]);
  if (!hasCapability(role, 'view_all_audit')) return <AdminOnly title="Operator Activity Report" onBack={onBack} />;
  const active = loaded?.filters ?? filters; const scope = active.stationId ? stations.find((station) => station.id === active.stationId)?.name ?? 'Selected station' : 'All accessible stations';
  return <ReportPageShell title="Operator Activity Report" subtitle="Created and last-updated logbook rows" onBack={onBack} contentRef={ref} actions={<ReportActions title="Operator Activity Report" contentRef={ref} rows={resource.rows} columns={columns} disabled={resource.loading} />} filters={<ReportFilters values={filters} options={{ stations, feeders: [] }} generating={resource.loading} onChange={setFilters} onGenerate={generate} />}>
    {loaded ? <ReportPreview meta={{ title: 'Operator Activity Report', stationScope: scope, periodLabel: getReportPeriodLabel(active), generatedAt: resource.generatedAt ?? new Date(), appliedFilters: [`From ${active.fromDate}`, `To ${active.toDate}`] }} summaryCards={cards} resource={resource} columns={columns} rowKey={(row) => row.id} onRetry={generate} pagination={{ page: loaded.page, pageSize: PAGE_SIZE, totalRows: loaded.total, onPageChange: (page) => { if (!resource.loading) load(loaded.filters, page, false); } }} /> : <div className="py-8 text-center text-sm text-slate-500">Select the scope and period, then generate the report.</div>}
    {loaded && <p className="mt-4 text-[11px] text-slate-500">“Subsequently updated” identifies a row whose current <code>updated_at</code> is later than <code>created_at</code>; edit history/counts are not available.</p>}
  </ReportPageShell>;
}

export function NotificationDeliveryReportPage({ onBack }: { onBack: () => void }) {
  const role = useAdminRole(); const { stations } = useApp(); const ref = useRef<HTMLDivElement>(null); const generation = useRef(0);
  const [filters, setFilters] = useState<ReportFilterValues>({ stationId: '', feederId: '', status: '', period: 'today', ...INITIAL_PERIOD });
  const [resource, setResource] = useState<ReportResource<NotificationDeliveryReportRow>>({ rows: [], loading: false, error: null, generatedAt: null }); const [summary, setSummary] = useState<NotificationDeliveryReportSummary | null>(null); const [loaded, setLoaded] = useState<Loaded | null>(null);
  const load = useCallback((next: ReportFilterValues, page: number, includeSummary: boolean) => { const request = ++generation.current; const { startIso, endIso } = getReportRangeIso(next); const stationId = next.stationId || null; const status = next.status || null; setResource((current) => ({ ...current, loading: true, error: null })); void (includeSummary ? Promise.all([api.getNotificationDeliveryReportPage(startIso, endIso, page, PAGE_SIZE, stationId, status), api.getNotificationDeliveryReportSummary(startIso, endIso, stationId, status)]) : Promise.all([api.getNotificationDeliveryReportPage(startIso, endIso, page, PAGE_SIZE, stationId, status), Promise.resolve(null)])).then(([detail, nextSummary]) => { if (request !== generation.current) return; if (nextSummary) setSummary(nextSummary); setLoaded({ filters: next, page, total: detail.total }); setResource({ rows: detail.rows, loading: false, error: null, generatedAt: new Date() }); }).catch((error: unknown) => { if (request === generation.current) setResource((current) => ({ ...current, loading: false, error: error instanceof Error ? error.message : 'Failed to generate the Notification Delivery report.' })); }); }, []);
  const generate = useCallback(() => { if (hasCapability(role, 'view_all_audit') && !resource.loading) load(filters, 0, true); }, [filters, load, resource.loading, role]);
  const columns = useMemo<ReportColumn<NotificationDeliveryReportRow>[]>(() => [
    { id: 'time', label: 'Event time (IST)', value: (row) => formatIst(row.event_time), csvValue: (row) => formatIst(row.event_time) }, { id: 'source', label: 'Event / source', value: (row) => row.source, csvValue: (row) => row.source }, { id: 'station', label: 'Station', value: (row) => row.station_name, csvValue: (row) => row.station_name },
    { id: 'intended', label: 'Intended recipients', align: 'right', value: (row) => String(row.intended_recipients), csvValue: (row) => row.intended_recipients }, { id: 'sent', label: 'Sent', align: 'right', value: (row) => String(row.sent), csvValue: (row) => row.sent }, { id: 'failed', label: 'Failed', align: 'right', value: (row) => String(row.failed), csvValue: (row) => row.failed }, { id: 'pending', label: 'Pending', align: 'right', value: (row) => String(row.pending), csvValue: (row) => row.pending }, { id: 'message', label: 'Delivery message', value: (row) => row.delivery_message ?? '—', csvValue: (row) => row.delivery_message },
  ], []);
  const cards = useMemo<ReportSummaryCard[]>(() => summary ? [{ label: 'Notification events', value: String(summary.events), tone: 'blue' }, { label: 'Intended recipients', value: String(summary.intended_recipients), tone: 'blue' }, { label: 'Sent / failed', value: `${summary.sent} / ${summary.failed}`, tone: summary.failed ? 'red' : 'green' }, { label: 'Pending', value: String(summary.pending), tone: summary.pending ? 'orange' : 'green' }] : [], [summary]);
  if (!hasCapability(role, 'view_all_audit')) return <AdminOnly title="Notification Delivery Report" onBack={onBack} />;
  const active = loaded?.filters ?? filters; const scope = active.stationId ? stations.find((station) => station.id === active.stationId)?.name ?? 'Selected station' : 'All accessible stations';
  return <ReportPageShell title="Notification Delivery Report" subtitle="Event-level recipient delivery outcomes" onBack={onBack} contentRef={ref} actions={<ReportActions title="Notification Delivery Report" contentRef={ref} rows={resource.rows} columns={columns} disabled={resource.loading} />} filters={<ReportFilters values={filters} options={{ stations, feeders: [], statusOptions: [{ value: 'SENT', label: 'Sent' }, { value: 'FAILED', label: 'Failed' }, { value: 'PENDING', label: 'Pending' }] }} generating={resource.loading} onChange={setFilters} onGenerate={generate} />}>
    {loaded ? <ReportPreview meta={{ title: 'Notification Delivery Report', stationScope: scope, periodLabel: getReportPeriodLabel(active), generatedAt: resource.generatedAt ?? new Date(), appliedFilters: [`From ${active.fromDate}`, `To ${active.toDate}`, `Status: ${active.status || 'All'}`] }} summaryCards={cards} resource={resource} columns={columns} rowKey={(row) => row.id} onRetry={generate} pagination={{ page: loaded.page, pageSize: PAGE_SIZE, totalRows: loaded.total, onPageChange: (page) => { if (!resource.loading) load(loaded.filters, page, false); } }} /> : <div className="py-8 text-center text-sm text-slate-500">Select the scope and period, then generate the report.</div>}
  </ReportPageShell>;
}
