import { useState } from 'react';
import { ArrowLeft, CheckCircle2, Clock3, Loader2, RefreshCw, UsersRound } from 'lucide-react';
import { AppHeader, PageBody, Screen } from '@/components/ui/Page';
import { DesktopPageHeading } from '@/components/layout/DesktopPageHeading';
import { useShiftDuty } from '@/hooks/useShiftDuty';

function formatDateTime(value: string | null | undefined) {
  if (!value) return '—';
  return new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
}
function shortId(value: string) { return `${value.slice(0, 8)}…`; }

export function CurrentShiftPage({ onBack }: { onBack: () => void }) {
  const shiftDuty = useShiftDuty();
  const [confirmEnd, setConfirmEnd] = useState(false);
  const { currentShift, myDutySession, operatorsOnDuty, plannedRoster, nextShift, station, loading, error, mutating } = shiftDuty;
  const isOnDuty = myDutySession?.status === 'ON_DUTY';

  const runStart = async () => { try { await shiftDuty.startDuty(); } catch { /* neutral state is set by the hook */ } };
  const runEnd = async () => { setConfirmEnd(false); try { await shiftDuty.endDuty(); } catch { /* neutral state is set by the hook */ } };

  return <Screen showStatusBar={false}>
    <AppHeader title="Current Shift" onBack={onBack} prominent className="rounded-b-[22px] bg-gradient-to-br from-[#0D47A1] to-[#1565C0] shadow-md lg:hidden" />
    <DesktopPageHeading title="Current Shift" subtitle="Server-confirmed duty and shift attendance" />
    <PageBody className="bg-[#F4F7FB] pb-28 lg:max-w-7xl lg:px-6 lg:py-6 lg:pb-10 xl:px-8">
      <div className="mx-auto max-w-4xl space-y-4 lg:max-w-none lg:space-y-5">
        <div className="flex items-center justify-between gap-3"><p className="text-sm font-medium text-slate-600">{station ? station.name : 'No authorized station selected'}</p><button type="button" onClick={() => void shiftDuty.refresh()} disabled={loading || mutating || !shiftDuty.hasStation} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold text-blue-700 shadow-sm disabled:opacity-60"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh</button></div>
        {error && <p role="alert" className="rounded-xl bg-red-50 px-4 py-3 text-sm font-medium text-red-700">{error}</p>}
        {!shiftDuty.hasStation && !loading && <EmptyState title="No station is available" detail="A current shift can be shown after your authorized station scope is available." />}
        {loading && !currentShift && shiftDuty.hasStation && <div className="grid min-h-44 place-items-center rounded-2xl bg-white"><Loader2 className="h-6 w-6 animate-spin text-blue-600" /></div>}
        {!loading && shiftDuty.hasStation && !currentShift && !error && <EmptyState title="No shift scheduled" detail="There is no current server-scheduled shift for this station." />}
        {nextShift && <section className="rounded-2xl border border-blue-100 bg-blue-50 p-4 lg:p-5"><p className="text-xs font-bold uppercase tracking-wide text-blue-700">Next scheduled shift</p><div className="mt-1 flex flex-wrap items-baseline justify-between gap-2"><h2 className="text-base font-bold text-slate-900">{nextShift.shift_name}</h2><p className="text-sm font-medium text-slate-700">Logical date: {nextShift.shift_date}</p></div><p className="mt-2 text-sm text-slate-700">{formatDateTime(nextShift.scheduled_start)} – {formatDateTime(nextShift.scheduled_end)}</p></section>}
        {currentShift && <>
          <section className="rounded-2xl bg-white p-4 shadow-sm lg:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Current Shift</p><h2 className="mt-1 text-xl font-bold text-slate-900">{currentShift.shift_name}</h2><p className="mt-1 text-sm text-slate-600">Logical date: {currentShift.shift_date}</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{currentShift.status}</span></div><div className="mt-5 grid gap-3 border-t border-slate-100 pt-4 sm:grid-cols-2"><Info label="Scheduled start" value={formatDateTime(currentShift.scheduled_start)} /><Info label="Scheduled end" value={formatDateTime(currentShift.scheduled_end)} /></div></section>
          <section className="rounded-2xl bg-white p-4 shadow-sm lg:p-6"><div className="flex items-center gap-2"><Clock3 className="h-5 w-5 text-blue-600" /><h2 className="text-base font-bold text-slate-900">My Duty</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Info label="Status" value={isOnDuty ? 'On Duty' : myDutySession?.status === 'ENDED' ? 'Ended' : 'Not Started'} /><Info label="Started" value={formatDateTime(myDutySession?.started_at)} /><Info label="Ended" value={formatDateTime(myDutySession?.ended_at)} /></div>{myDutySession && <p className="mt-3 text-sm text-slate-600">Role: <span className="font-semibold text-slate-800">{myDutySession.shift_role === 'IN_CHARGE' ? 'Shift In-Charge' : 'Member'}</span></p>}<div className="mt-5 flex flex-wrap gap-3 border-t border-slate-100 pt-4">{!myDutySession ? <button type="button" disabled={mutating} onClick={() => void runStart()} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-blue-700 px-4 text-sm font-bold text-white disabled:opacity-60"><CheckCircle2 className="h-4 w-4" />{mutating ? 'Starting…' : 'Start Duty'}</button> : isOnDuty ? <button type="button" disabled={mutating} onClick={() => setConfirmEnd(true)} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-red-200 bg-white px-4 text-sm font-bold text-red-700 disabled:opacity-60">{mutating ? 'Ending…' : 'End Duty'}</button> : <p className="text-sm font-medium text-slate-600">Your duty session has ended for this shift.</p>}</div></section>
          <section className="overflow-hidden rounded-2xl bg-white shadow-sm"><div className="flex items-center gap-2 border-b border-slate-100 p-4 lg:px-6"><UsersRound className="h-5 w-5 text-blue-600" /><div><h2 className="text-base font-bold text-slate-900">Planned Roster</h2><p className="text-xs text-slate-500">Planned team and server-confirmed attendance</p></div></div>{plannedRoster.length ? <div className="divide-y divide-slate-100">{plannedRoster.map((assignment) => { const attendance = operatorsOnDuty.find((session) => session.user_id === assignment.user_id); return <div key={assignment.id} className="grid gap-1 p-4 text-sm sm:grid-cols-[minmax(0,1fr)_auto_auto] sm:items-center sm:gap-4 lg:px-6"><p className="font-semibold text-slate-800">{assignment.user_id === myDutySession?.user_id ? 'You' : assignment.full_name}</p><p className="text-slate-600">{assignment.duty_role === 'IN_CHARGE' ? 'Shift In-Charge' : 'Member'}</p><p className={attendance?.status === 'ON_DUTY' ? 'font-semibold text-emerald-700' : attendance?.status === 'ENDED' ? 'font-semibold text-slate-500' : 'font-semibold text-amber-700'}>{attendance?.status === 'ON_DUTY' ? 'On Duty' : attendance?.status === 'ENDED' ? `Ended ${formatDateTime(attendance.ended_at)}` : 'Not started'}</p></div>; })}</div> : <p className="p-5 text-sm text-slate-600">No planned roster has been assigned for this shift.</p>}</section>
          <section className="overflow-hidden rounded-2xl bg-white shadow-sm"><div className="flex items-center gap-2 border-b border-slate-100 p-4 lg:px-6"><UsersRound className="h-5 w-5 text-blue-600" /><div><h2 className="text-base font-bold text-slate-900">Actual Attendance</h2><p className="text-xs text-slate-500">Duty sessions recorded for this shift</p></div></div>{operatorsOnDuty.length ? <div className="divide-y divide-slate-100">{operatorsOnDuty.map((session) => { const planned = plannedRoster.find((assignment) => assignment.user_id === session.user_id); return <div key={session.id} className="grid gap-1 p-4 text-sm sm:grid-cols-[minmax(0,1fr)_auto_auto_auto] sm:items-center sm:gap-4 lg:px-6"><p className="font-semibold text-slate-800">{session.user_id === myDutySession?.user_id ? 'You' : planned?.full_name ?? `Unplanned participant ${shortId(session.user_id)}`}</p><p className="text-slate-600">{session.shift_role === 'IN_CHARGE' ? 'Shift In-Charge' : 'Member'}{!planned && <span className="ml-1 text-amber-700">(Unplanned)</span>}</p><p className="text-slate-600">Started {formatDateTime(session.started_at)}</p><p className={session.status === 'ON_DUTY' ? 'font-semibold text-emerald-700' : 'font-semibold text-slate-500'}>{session.status === 'ON_DUTY' ? 'On Duty' : `Ended ${formatDateTime(session.ended_at)}`}</p></div>; })}</div> : <p className="p-5 text-sm text-slate-600">No duty sessions have been recorded for this shift.</p>}</section>
        </>}
      </div>
    </PageBody>
    {confirmEnd && <div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/40 p-5"><div role="dialog" aria-modal="true" className="w-full max-w-sm rounded-2xl bg-white p-5 shadow-xl"><h2 className="text-lg font-bold text-slate-900">End duty?</h2><p className="mt-2 text-sm text-slate-600">This ends only your duty session. It does not log you out or close the shift.</p><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={() => setConfirmEnd(false)} className="min-h-10 rounded-xl px-3 text-sm font-semibold text-slate-700">Cancel</button><button type="button" onClick={() => void runEnd()} className="min-h-10 rounded-xl bg-red-600 px-4 text-sm font-bold text-white">End Duty</button></div></div></div>}
  </Screen>;
}

function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-sm font-medium text-slate-800">{value}</p></div>; }
function EmptyState({ title, detail }: { title: string; detail: string }) { return <section className="rounded-2xl bg-white p-6 text-center shadow-sm"><Clock3 className="mx-auto h-7 w-7 text-slate-400" /><h2 className="mt-3 text-base font-bold text-slate-800">{title}</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-slate-600">{detail}</p></section>; }
