import { supabase } from '@/services/supabase';
import type { CreateShutdownInput, ShutdownKpis, ShutdownListFilters, ShutdownPurpose, ShutdownRecord, ShutdownReportFilters, ShutdownStatus, ShutdownType } from './types';

type RpcRow = Record<string, unknown>;
function text(row:RpcRow,key:string,fallback=''){const value=row[key];return typeof value==='string'?value:fallback;}
function nullableText(row:RpcRow,key:string){const value=row[key];return typeof value==='string'?value:null;}
function nullableNumber(row:RpcRow,key:string){const value=row[key];const numeric=typeof value==='number'?value:typeof value==='string'&&value.trim()!==''?Number(value):NaN;return Number.isFinite(numeric)?numeric:null;}
function mapRow(value:unknown):ShutdownRecord{const row=value as RpcRow;return {id:text(row,'id'),sdNumber:text(row,'sd_number'),stationId:text(row,'station_id'),stationName:text(row,'station_name'),feederId:nullableText(row,'feeder_id'),feederName:nullableText(row,'feeder_name'),equipmentName:text(row,'equipment_name',nullableText(row,'feeder_name')??''),shutdownType:text(row,'shutdown_type') as ShutdownType,purpose:text(row,'purpose') as ShutdownPurpose,workDescription:text(row,'work_description'),plannedStart:text(row,'planned_start'),expectedRestoration:text(row,'expected_restoration'),remarks:text(row,'remarks'),affectedConsumerCount:nullableNumber(row,'affected_consumer_count'),affectedLoadMw:nullableNumber(row,'affected_load_mw'),alternateSourceAvailability:nullableText(row,'alternate_source_availability') as ShutdownRecord['alternateSourceAvailability'],requestedByUserId:text(row,'requested_by'),requestedByName:text(row,'requested_by_name'),requestedAt:text(row,'requested_at'),status:text(row,'status') as ShutdownStatus,decisionByUserId:nullableText(row,'decision_by')??undefined,decisionByName:nullableText(row,'decision_by_name')??undefined,decisionAt:nullableText(row,'decision_at')??undefined,decisionRemarks:nullableText(row,'decision_remarks')??undefined,canDecide:typeof row.can_decide==='boolean'?row.can_decide:undefined,totalCount:typeof row.total_count==='number'?row.total_count:undefined};}
function friendly(error:{message?:string;code?:string}|null){const raw=(error?.message??'').toLowerCase();if(raw.includes('already been decided'))return 'This request was already decided. Refresh and try again.';if(raw.includes('own shutdown'))return 'You cannot approve or reject your own request.';if(raw.includes('outside')||error?.code==='42501')return 'You do not have permission for this shutdown request.';if(raw.includes('rejection remarks'))return 'Rejection remarks are required.';if(raw.includes('not found'))return 'This shutdown request is no longer available.';return 'Shutdown Management is temporarily unavailable. Please try again.';}
async function rows(name:string,args:RpcRow){const {data,error}=await supabase.rpc(name,args);if(error)throw new Error(friendly(error));const mapped=(Array.isArray(data)?data:[]).map(mapRow);return {rows:mapped,total:mapped[0]?.totalCount??0};}
export const shutdownService={
 listDashboard:(f:ShutdownListFilters)=>rows('list_shutdown_dashboard_requests',{p_status:f.status??null,p_search:f.search||null,p_station_id:f.stationId||null,p_from_date:f.fromDate||null,p_to_date:f.toDate||null,p_limit:f.limit,p_offset:f.offset}),
 async getKpis():Promise<ShutdownKpis>{const {data,error}=await supabase.rpc('get_shutdown_dashboard_kpis');if(error)throw new Error(friendly(error));const row=(Array.isArray(data)?data[0]:data) as RpcRow|undefined;return {total:Number(row?.total??0),pendingApproval:Number(row?.pending_approval??0),approved:Number(row?.approved??0),rejected:Number(row?.rejected??0),cancelled:Number(row?.cancelled??0)};},
 listMine:(f:Omit<ShutdownListFilters,'stationId'>)=>rows('list_my_shutdown_requests',{p_status:f.status??null,p_search:f.search||null,p_from_date:f.fromDate||null,p_to_date:f.toDate||null,p_limit:f.limit,p_offset:f.offset}),
 async get(id:string){const {data,error}=await supabase.rpc('get_shutdown_request',{p_shutdown_id:id});if(error)throw new Error(friendly(error));const row=Array.isArray(data)?data[0]:data;if(!row)throw new Error('This shutdown request is no longer available.');return mapRow(row);},
 async create(input:CreateShutdownInput){const {data,error}=await supabase.rpc('create_shutdown_request',{p_station_id:input.stationId,p_feeder_id:input.feederId||null,p_equipment_name:input.equipmentName||null,p_shutdown_type:input.shutdownType,p_purpose:input.purpose,p_work_description:input.workDescription,p_planned_start:input.plannedStart,p_expected_restoration:input.expectedRestoration,p_remarks:input.remarks||null,p_affected_consumer_count:input.affectedConsumerCount,p_affected_load_mw:input.affectedLoadMw,p_alternate_source_availability:input.alternateSourceAvailability});if(error)throw new Error(friendly(error));return mapRow(Array.isArray(data)?data[0]:data);},
 async approve(id:string,remarks:string){const {data,error}=await supabase.rpc('approve_shutdown_request',{p_shutdown_id:id,p_decision_remarks:remarks||null});if(error)throw new Error(friendly(error));return mapRow(Array.isArray(data)?data[0]:data);},
 async reject(id:string,remarks:string){const {data,error}=await supabase.rpc('reject_shutdown_request',{p_shutdown_id:id,p_decision_remarks:remarks});if(error)throw new Error(friendly(error));return mapRow(Array.isArray(data)?data[0]:data);},
 listReport:(f:ShutdownReportFilters)=>rows('list_shutdown_report_requests',{p_from_date:f.fromDate||null,p_to_date:f.toDate||null,p_station_id:f.stationId||null,p_status:f.status==='ALL'?null:f.status,p_feeder_id:f.feederId||null,p_equipment:f.equipmentName||null,p_requester:f.requestedByUserId||null,p_limit:f.limit,p_offset:f.offset}),
};
