-- Extend the existing Load Analysis ranking read contract with voltage/current.
drop function if exists public.get_load_analysis_station_ranking(timestamptz, timestamptz);
drop function if exists public.get_load_analysis_feeder_ranking(timestamptz, timestamptz, uuid);

create or replace function public.get_load_analysis_station_ranking(p_start timestamptz, p_end timestamptz)
returns table(station_id uuid, station_name text, peak_mw numeric, minimum_voltage_kv numeric, maximum_current_a numeric, minimum_power_factor numeric, entered_feeder_hours bigint, expected_feeder_hours bigint, completeness_percent numeric)
language sql stable security invoker set search_path = public as $$
with accessible as (select station_id from public.get_my_accessible_station_ids()), scope_stations as (select s.id station_id,s.name station_name from public.stations s join accessible a on a.station_id=s.id where coalesce(s.active,true)), scope_feeders as (select f.id feeder_id,f.station_id from public.feeders f join scope_stations s on s.station_id=f.station_id where coalesce(f.active,true)), base as (select distinct on (l.feeder_id,date_trunc('hour',l.actual_event_time at time zone 'Asia/Kolkata')) l.station_id,l.feeder_id,l.mw,l.voltage_kv,l.current_a,l.power_factor,date_trunc('hour',l.actual_event_time at time zone 'Asia/Kolkata') local_hour from public.log_book_entries l join scope_feeders f on f.feeder_id=l.feeder_id where l.actual_event_time>=p_start and l.actual_event_time<p_end order by l.feeder_id,date_trunc('hour',l.actual_event_time at time zone 'Asia/Kolkata'),l.updated_at desc,l.id desc), hours as (select coalesce(sum(case when d.day < (now() at time zone 'Asia/Kolkata')::date then 24 when d.day=(now() at time zone 'Asia/Kolkata')::date then least(24,extract(hour from now() at time zone 'Asia/Kolkata')::integer+1) else 0 end),0)::bigint count from generate_series((p_start at time zone 'Asia/Kolkata')::date,((p_end at time zone 'Asia/Kolkata')::date-1),interval '1 day') d(day)), feeder_counts as (select station_id,count(*)::bigint feeder_count from scope_feeders group by station_id), entered as (select station_id,count(*)::bigint entered_feeder_hours,min(voltage_kv) filter(where voltage_kv is not null) minimum_voltage_kv,max(current_a) filter(where current_a is not null) maximum_current_a,min(power_factor) filter(where power_factor is not null) minimum_power_factor from base group by station_id), peaks as (select station_id,max(mw) peak_mw from base group by station_id)
select s.station_id,s.station_name,p.peak_mw,e.minimum_voltage_kv,e.maximum_current_a,e.minimum_power_factor,coalesce(e.entered_feeder_hours,0),coalesce(f.feeder_count,0)*hours.count,case when coalesce(f.feeder_count,0)*hours.count>0 then round(least(100,coalesce(e.entered_feeder_hours,0)::numeric*100/(f.feeder_count*hours.count)),1) else 0 end from scope_stations s left join feeder_counts f using(station_id) left join entered e using(station_id) left join peaks p using(station_id) cross join hours;
$$;

grant execute on function public.get_load_analysis_station_ranking(timestamptz, timestamptz) to authenticated;

create or replace function public.get_load_analysis_feeder_ranking(p_start timestamptz, p_end timestamptz, p_station_id uuid)
returns table(feeder_id uuid, feeder_name text, peak_mw numeric, minimum_voltage_kv numeric, maximum_current_a numeric, minimum_power_factor numeric, entered_feeder_hours bigint, expected_feeder_hours bigint, completeness_percent numeric)
language sql stable security invoker set search_path = public as $$
with accessible as (select station_id from public.get_my_accessible_station_ids()), scope_feeders as (select f.id feeder_id,f.name feeder_name from public.feeders f join accessible a on a.station_id=f.station_id where f.station_id=p_station_id and coalesce(f.active,true)), base as (select distinct on (l.feeder_id,date_trunc('hour',l.actual_event_time at time zone 'Asia/Kolkata')) l.feeder_id,l.mw,l.voltage_kv,l.current_a,l.power_factor,date_trunc('hour',l.actual_event_time at time zone 'Asia/Kolkata') local_hour from public.log_book_entries l join scope_feeders f on f.feeder_id=l.feeder_id where l.actual_event_time>=p_start and l.actual_event_time<p_end order by l.feeder_id,date_trunc('hour',l.actual_event_time at time zone 'Asia/Kolkata'),l.updated_at desc,l.id desc), hours as (select coalesce(sum(case when d.day < (now() at time zone 'Asia/Kolkata')::date then 24 when d.day=(now() at time zone 'Asia/Kolkata')::date then least(24,extract(hour from now() at time zone 'Asia/Kolkata')::integer+1) else 0 end),0)::bigint count from generate_series((p_start at time zone 'Asia/Kolkata')::date,((p_end at time zone 'Asia/Kolkata')::date-1),interval '1 day') d(day)), entered as (select feeder_id,count(*)::bigint entered_feeder_hours,min(voltage_kv) filter(where voltage_kv is not null) minimum_voltage_kv,max(current_a) filter(where current_a is not null) maximum_current_a,min(power_factor) filter(where power_factor is not null) minimum_power_factor,max(mw) peak_mw from base group by feeder_id)
select f.feeder_id,f.feeder_name,e.peak_mw,e.minimum_voltage_kv,e.maximum_current_a,e.minimum_power_factor,coalesce(e.entered_feeder_hours,0),hours.count,case when hours.count>0 then round(least(100,coalesce(e.entered_feeder_hours,0)::numeric*100/hours.count),1) else 0 end from scope_feeders f left join entered e using(feeder_id) cross join hours;
$$;

grant execute on function public.get_load_analysis_feeder_ranking(timestamptz, timestamptz, uuid) to authenticated;
