-- Stage 10A: explicit, fail-closed audit scope on the existing ledger.
ALTER TABLE public.administration_audit_log ADD COLUMN IF NOT EXISTS station_id uuid REFERENCES public.stations(id) ON DELETE SET NULL, ADD COLUMN IF NOT EXISTS org_unit_id uuid REFERENCES public.org_units(id) ON DELETE SET NULL, ADD COLUMN IF NOT EXISTS visibility text NOT NULL DEFAULT 'ADMIN_GLOBAL' CHECK (visibility IN ('SCOPED','ADMIN_GLOBAL','SUPER_ADMIN_ONLY')), ADD COLUMN IF NOT EXISTS old_values jsonb, ADD COLUMN IF NOT EXISTS new_values jsonb;
UPDATE public.administration_audit_log SET old_values=coalesce(old_values,before_data),new_values=coalesce(new_values,after_data),visibility=CASE WHEN entity_type IN ('ORG_UNIT','STATION','FEEDER','FEEDER_THRESHOLD','STATION_OFFICE_MAPPING') THEN 'ADMIN_GLOBAL' WHEN entity_type='APP_USER' AND coalesce(after_data->>'role','')='SUPER_ADMIN' THEN 'SUPER_ADMIN_ONLY' ELSE 'ADMIN_GLOBAL' END WHERE old_values IS NULL OR new_values IS NULL;
CREATE OR REPLACE FUNCTION public.get_my_accessible_org_unit_ids() RETURNS TABLE(org_unit_id uuid) LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ WITH RECURSIVE roots AS (SELECT uou.org_unit_id FROM public.user_org_units uou JOIN public.org_units ou ON ou.id=uou.org_unit_id WHERE uou.user_id=auth.uid() AND uou.active AND ou.active), tree AS (SELECT org_unit_id, ARRAY[org_unit_id] AS path FROM roots UNION ALL SELECT child.id, tree.path || child.id FROM tree JOIN public.org_units child ON child.parent_id=tree.org_unit_id WHERE child.active AND NOT child.id=ANY(tree.path)) SELECT DISTINCT org_unit_id FROM tree; $$;
CREATE OR REPLACE FUNCTION public.audit_scope_allowed(p_station uuid,p_office uuid,p_visibility text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT CASE public.get_my_role() WHEN 'SUPER_ADMIN'::public.app_user_role THEN true WHEN 'ADMIN'::public.app_user_role THEN p_visibility IN ('SCOPED','ADMIN_GLOBAL') WHEN 'FIELD_OFFICER'::public.app_user_role THEN p_visibility='SCOPED' AND ((p_station IS NOT NULL AND EXISTS(SELECT 1 FROM public.get_my_accessible_station_ids() s WHERE s.station_id=p_station)) OR (p_office IS NOT NULL AND EXISTS(SELECT 1 FROM public.get_my_accessible_org_unit_ids() o WHERE o.org_unit_id=p_office))) ELSE false END; $$;
DROP POLICY IF EXISTS "Administrators can view administration audit" ON public.administration_audit_log; DROP POLICY IF EXISTS "Role scoped administration audit read" ON public.administration_audit_log;
CREATE POLICY "Scoped administration audit read" ON public.administration_audit_log FOR SELECT TO authenticated USING (public.audit_scope_allowed(station_id,org_unit_id,visibility));
GRANT EXECUTE ON FUNCTION public.get_my_accessible_org_unit_ids() TO authenticated;
CREATE OR REPLACE FUNCTION public.prevent_administration_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Administration audit records are append-only' USING ERRCODE='42501'; END; $$;
DROP TRIGGER IF EXISTS trg_prevent_administration_audit_mutation ON public.administration_audit_log; CREATE TRIGGER trg_prevent_administration_audit_mutation BEFORE UPDATE OR DELETE ON public.administration_audit_log FOR EACH ROW EXECUTE FUNCTION public.prevent_administration_audit_mutation();
CREATE OR REPLACE FUNCTION public.save_feeder_threshold(p_id uuid,p_feeder_id uuid,p_parameter_code text,p_min numeric,p_max numeric,p_reason text DEFAULT NULL) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE v_id uuid; v_old public.feeder_thresholds%ROWTYPE; v_station uuid; BEGIN IF public.get_my_role() NOT IN ('FIELD_OFFICER'::public.app_user_role,'ADMIN'::public.app_user_role,'SUPER_ADMIN'::public.app_user_role) OR NOT EXISTS(SELECT 1 FROM public.get_my_manageable_feeder_station_ids() s JOIN public.feeders f ON f.station_id=s.station_id WHERE f.id=p_feeder_id AND f.active) THEN RAISE EXCEPTION 'Threshold is outside your permitted scope' USING ERRCODE='42501'; END IF; SELECT f.station_id INTO v_station FROM public.feeders f WHERE f.id=p_feeder_id AND f.active; IF v_station IS NULL THEN RAISE EXCEPTION 'Threshold is outside your permitted scope' USING ERRCODE='42501'; END IF; IF p_min IS NULL AND p_max IS NULL OR p_min IS NOT NULL AND p_max IS NOT NULL AND p_min>p_max THEN RAISE EXCEPTION 'Provide a valid minimum and/or maximum threshold' USING ERRCODE='22023'; END IF; SELECT * INTO v_old FROM public.feeder_thresholds WHERE feeder_id=p_feeder_id AND parameter_code=p_parameter_code FOR UPDATE; INSERT INTO public.feeder_thresholds(id,feeder_id,parameter_code,min_value,max_value) VALUES(coalesce(p_id,gen_random_uuid()),p_feeder_id,p_parameter_code,p_min,p_max) ON CONFLICT(feeder_id,parameter_code) DO UPDATE SET min_value=excluded.min_value,max_value=excluded.max_value,updated_at=now() RETURNING id INTO v_id; INSERT INTO public.administration_audit_log(actor_id,action,entity_type,entity_id,station_id,visibility,old_values,new_values,reason) SELECT auth.uid(),'SAVE','FEEDER_THRESHOLD',v_id,v_station,'SCOPED',CASE WHEN v_old.id IS NULL THEN NULL ELSE to_jsonb(v_old) END,to_jsonb(ft),coalesce(nullif(btrim(coalesce(p_reason,'')),''),'No reason supplied') FROM public.feeder_thresholds ft WHERE ft.id=v_id; RETURN v_id; END; $$;
CREATE OR REPLACE FUNCTION public.update_global_notification_config(p_id uuid,p_active boolean,p_max_unit_type text,p_reason text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE v_old public.notification_config%ROWTYPE; BEGIN IF public.get_my_role() NOT IN ('ADMIN'::public.app_user_role,'SUPER_ADMIN'::public.app_user_role) THEN RAISE EXCEPTION 'Only Admin or Super Admin may update global notification settings' USING ERRCODE='42501'; END IF; IF NOT EXISTS(SELECT 1 FROM public.get_org_unit_types() t WHERE t.unit_type=p_max_unit_type) THEN RAISE EXCEPTION 'Unsupported organisational boundary' USING ERRCODE='22023'; END IF; IF btrim(coalesce(p_reason,''))='' THEN RAISE EXCEPTION 'A confirmation reason is required' USING ERRCODE='22023'; END IF; SELECT * INTO v_old FROM public.notification_config WHERE id=p_id FOR UPDATE; IF v_old.id IS NULL THEN RAISE EXCEPTION 'Notification configuration not found' USING ERRCODE='P0002'; END IF; UPDATE public.notification_config SET active=p_active,max_unit_type=p_max_unit_type,updated_at=now(),updated_by=auth.uid() WHERE id=p_id; INSERT INTO public.administration_audit_log(actor_id,action,entity_type,entity_id,visibility,old_values,new_values,reason) SELECT auth.uid(),'UPDATE','GLOBAL_NOTIFICATION_CONFIG',p_id,'ADMIN_GLOBAL',to_jsonb(v_old),to_jsonb(nc),p_reason FROM public.notification_config nc WHERE nc.id=p_id; END; $$;
GRANT EXECUTE ON FUNCTION public.save_feeder_threshold(uuid,uuid,text,numeric,numeric,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_global_notification_config(uuid,boolean,text,text) TO authenticated;
